=== GameCzar485/Portfolio/IT440 - Database Management Systems/Assignment 6/ch15_problem8_Young.dtd
<!ELEMENT CustomerExchange (Customer+)>
<!ELEMENT Customer (CUS_CODE, CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE, CUS_PHONE, CUS_INSURE_TYPE, CUS_INSURE_AMT, CUS_RENEW_DATE, AGENT_CODE)>
<!ELEMENT CUS_CODE         (#PCDATA)>
<!ELEMENT CUS_LNAME        (#PCDATA)>
<!ELEMENT CUS_FNAME        (#PCDATA)>
<!ELEMENT CUS_INITIAL      (#PCDATA)>
<!ELEMENT CUS_AREACODE     (#PCDATA)>
<!ELEMENT CUS_PHONE        (#PCDATA)>
<!ELEMENT CUS_INSURE_TYPE  (#PCDATA)>
<!ELEMENT CUS_INSURE_AMT   (#PCDATA)>
<!ELEMENT CUS_RENEW_DATE   (#PCDATA)>
<!ELEMENT AGENT_CODE       (#PCDATA)>

=== GameCzar485/Portfolio/IT440 - Database Management Systems/Assignment 6/ch15_problem8_Young.xml
<?xml version="1.0">
<!DOCTYPE Customer SYSTEM "ch15_problem8_Young.dtd">
<CustomerExchange>
    <Customer>
        <CUS_CODE>10020</CUS_CODE>
        <CUS_LNAME>Johnson</CUS_LNAME>
        <CUS_FNAME>Jan</CUS_FNAME>
        <CUS_INITIAL>W</CUS_INITIAL>
        <CUS_AREACODE>612</CUS_AREACODE>
        <CUS_PHONE>865-3420</CUS_PHONE>
        <CUS_INSURE_TYPE>T2</CUS_INSURE_TYPE>
        <CUS_INPUT_AMT>300</CUS_INPUT_AMT>
        <CUS_RENEW_DATE>11/23/2018</CUS_RENEW_DATE>
        <AGENT_CODE>502</AGENT_CODE>
    </Customer>
</CustomerExchange>
